### ISSUE TITLE
Automate creation of k8s cluster

### ISSUE THREAD

**Issue by agalitsyn** [agalitsyn/yagoda#1]
K8s should lay on some infrastructure.

Need:
- Create `Vagrantfile` with 3+ VMs
- Include network settings
- Provision k8s on top of it using any vagrant provisioner

Why vagrant?
- Flexible network setup
- Virtualbox provider is kinda universal for all OS
- Ability to use any cloud provider for deploy demo set
- Ability to reuse provision scripts on any provider

**Comment by alexey-medvedchikov** [comment]
5 VMs:
- 1 controller, 1 etcd (small resource limits)
- 3 workers for running cassandra

**Comment by agalitsyn** [comment]
Also we need place for docker-registry.

My branch is still WIP, but I've added https://github.com/agalitsyn/yagoda/tree/try-ds-with-cass/registry
It will be rebased as fix for https://github.com/agalitsyn/yagoda/issues/5

**Comment by agalitsyn** [comment]
Also, we can use terraform scripts, see reference at https://github.com/kelseyhightower/kubestack

**Comment by agalitsyn** [comment]
Done via https://github.com/agalitsyn/yagoda/pull/24
