### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by agalitsyn** [agalitsyn/yagoda#15]
Logging should be available by kubectl tool, so we should ensure that all needed info is recorded and accessible

**Comment by alexey-medvedchikov** [comment]
AFAIK, to make logs available for k8s we need to use container provider standard logging method. And we are using docker, so just write it to stdout/stderr. One thing we need to know: does kubectl retrieves stderr, and if it does, does it merges stderr and stdout?

**Comment by alexey-medvedchikov** [comment]
`kubectl logs` retrieves both docker stderr and stdout, and yes it merges both streams to stdout. Nothing to do here, just log in docker usual manner.
