### ISSUE TITLE
Research networking setup

### ISSUE THREAD

**Issue by agalitsyn** [agalitsyn/yagoda#2]
Cassandra pods on different k8s hosts should have an ability to communicate to each other.

Ideally we should have 2 interfaces - one for peer gossip and handoffs and another one for client data flow.

Overlay network is really slow, host network brings limitations, for example pod don't have an ip.

**Comment by alexey-medvedchikov** [comment]
[K8S providers support](http://kubernetes.io/docs/getting-started-guides/)

Overlay network:
:heavy_plus_sign: relatively simple setup
:heavy_plus_sign: supported by project
:heavy_minus_sign: sagnificant performance penalty in latency and throughput

Dynamic routing:
:heavy_plus_sign: no performance penalty
:heavy_minus_sign: complex setup, required smth like quagga or calico running on each node
:heavy_minus_sign: experimental, supported by 3rd party tools

Bare network:
:heavy_plus_sign: no performance penalty
:heavy_plus_sign: no setup at all, nodes already have network anyway
:heavy_minus_sign: limitation in many ways (downwardAPI, smth wrong with svc, container image must be aware of this setup)

It's useless to start multiple C\* on one node (vnodes for ring balancing), so main overlay and DR feature (dedicated address per container) is useless.
I think we can fight limitations, and actually gain some flexibility by managing network on our own. Like multiple links, jumbos, etc.

Just using hostnetwork.
