### ISSUE TITLE
Research discovery by gossip without custom SeedProvider

### ISSUE THREAD

**Issue by agalitsyn** [agalitsyn/yagoda#3]
k8s team have this customization in Cassandra https://github.com/kubernetes/kubernetes/tree/master/examples/cassandra/java

Aim of research: find how to do that without modifying software deployed on the cluster, because such plugins don't exists for other software

**Comment by alexey-medvedchikov** [comment]
[DataStax docs](http://docs.datastax.com/en/cassandra/3.x/cassandra/architecture/archGossipAbout.html) has nice explanation on purpose of seeds and gossip proto. And actually gossip isn't ip broadcast: it's peer-to-peer.
In short: we need to properly configure gossip and specify few seed nodes in every datacenter.

**Comment by agalitsyn** [comment]
I found an example https://github.com/vyshane/cassandra-kubernetes
It uses headless service from k8s and DNS for discovery. Nice, but not enough, DNS can be absent, and I don't want to patch Image

**Comment by agalitsyn** [comment]
Limitations of our solution will be:
1. 1 DC
2. 1 cluster
3. 1 rack

C\* discovery way - `GossipingPropertyFileSnitch`, read about it [here](https://docs.datastax.com/en/cassandra/3.x/cassandra/architecture/archsnitchGossipPF.html)

We can use conjuction of env vars to boostrap multi-node cluster:
- `CASSANDRA_BROADCAST_ADDRESS`for ip of current nodes (already set automatically)
- `CASSANDRA_SEEDS` for list of specific nodes. Not all nodes should be seeds. See [doc](http://docs.datastax.com/en/cassandra/3.x/cassandra/architecture/archGossipAbout.html)

Also I refer to [official docker image](https://hub.docker.com/_/cassandra/)
