### ISSUE TITLE
Research basic k8s resource for deployment

### ISSUE THREAD

**Issue by agalitsyn** [agalitsyn/yagoda#7]
Options:
1. Daemon set - http://kubernetes.io/docs/admin/daemons/
2. Replica set & deployment - http://kubernetes.io/docs/user-guide/replicasets/ and http://kubernetes.io/docs/user-guide/deployments/

1 - fits to database, because DS = one per host and starts before application pods.
2 - fits because it have "finished" event of deployment. Also it can be integrated with autoscaler and use rolling updates. And ability to scale instances without creating a new host.

So, question - what fits better for cassandra?

**Comment by alexey-medvedchikov** [comment]
I think DS rolling update can be made with something like [this for RC](http://kubernetes.io/docs/user-guide/replication-controller/#rolling-updates). We just need some mechanism to connect old and new C\* versions between two different DS. Versions can be controlled via node labels:
1. Got N nodes labelled `role=cassandra-3.0.5`
2. Create DS with label filter `role=cassandra-3.1.0` (whatever)
3. `kubectl label node $node role- && kubectl label node $node role=cassandra-3.1.0`
4. Wait until new C\* available
5. While there is nodes with `role=cassandra-3.0.5`, goto 3.

This can be made in batches.

**Comment by alexey-medvedchikov** [comment]
On the other hand RS can use node labels like DS. And deployment has much more options to control update process, and it's already automated on server side.
With RS by labels we can control how much nodes potentially available for C*, and actual number of nodes can be controlled separately. And DS just populates this nodes with C*. There's more: [RS befriends with Autoscaler](http://kubernetes.io/docs/user-guide/replicasets/#replica-set-as-an-horizontal-pod-autoscaler-target).

I think we'll try RS. I don't see any DS pros in here, but drawbacks are significent.

**Comment by agalitsyn** [comment]
My proposal is _not_ to use Replica Set (RS) for Cassandra (C) and use Daemon Set (DS) and Node Selector (NS).
Reasons:
1. Pods scheduler uses quite simple algorithms, you can check it out here
     \* [generic_scheduler.go](https://github.com/kubernetes/kubernetes/blob/release-1.2/plugin/pkg/scheduler/generic_scheduler.go#L128)
     \* [scheduler-policy-config.json](https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/scheduler-policy-config.json)
     \* [stackoverflow](http://stackoverflow.com/questions/28857993/how-does-kubernetes-scheduler-work/28874577)
C is backing-service, placement of nodes should be more elaborate. See [doc](http://docs.datastax.com/en/cassandra/3.0/cassandra/planning/planPlanningEC2.html). I cant find solution in k8s, that will provide reliable behavior, except DS and NS.
2. It's ok to add C instances by adding nodes, see [doc](http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsAddNodeToCluster.html)
3. [Horizontal pod autoscaler](http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/) is useless for C because of too basic resource controller.
4. C upgrade can be in-place, see [doc](http://docs.datastax.com/en/latest-upgrade/upgrade/cassandra/upgradeCassandraDetails.html). Many steps actually, if you want to automate it, script should be quite clever, and it's not related to k8s at all.
5. Arch of C writes data and replicates it. It uses huge MemTable in RAM and SSTable and Commit log on disk. So with RS we can have 2 C pods on 1 node, which store the same part of data both in RAM and on disk on 1 machine. Inefficient resource consumption, and if node will go down, we can loose data, because replication factor for our task probably will be 3, and algorithm - probably quorum.
6, No need to automatically replicate C instances, she can take care of herself :)

**Comment by agalitsyn** [comment]
Also you can check out thread `https://github.com/kubernetes/kubernetes/issues/1518`
